### ISSUE TITLE
我发现了一个bug

### ISSUE THREAD

**Issue by AstroAir** [agalasso/phd2client#2]
我尝试使用c++示例库中的程序，但是连接设备这个一部分总是不行，无法连接上设备，是不是代码有错误，我已尝试了许多次，好像python也有相同的情况。

**Comment by agalasso** [comment]
can you please provide more specific information.  what exactly is not working?
do you have a way for me to try to reproduce the problem?

**Comment by AstroAir** [comment]
主要的问题是，如果整个程序中有连接设备的代码，那么这个程序就无法执行，或者是闪一下就没有了（在模拟器中执行），我觉得可能是变量的类型有问题，也可鞥能是示例代码有错误，我是直接使用示例代码的。

**Comment by agalasso** [comment]
@AstroAir I see that you closed this issue. What was the resolution?

**Comment by AstroAir** [comment]
@agalasso I open this issue again .I am thinking about how to write a API to recive message from PHD2 instead of using telnet (This is too slow,and work not very well).
I found this code in [https://github.com/agalasso/phd2client/blob/master/cxx/guider.cpp](url):
`else if (e == "GuideStep")
    {
        GuideStats stats;
        if (accum_active)
        {
            accum_ra.Add(ev["RADistanceRaw"].asDouble());
            accum_dec.Add(ev["DECDistanceRaw"].asDouble());
            accum_get_stats(&stats, accum_ra, accum_dec);
        }
        std::unique_lock<decltype(m_mutex)> _lock(m_mutex);
        AppState = "Guiding";
        AvgDist = ev["AvgDist"].asDouble();
        if (accum_active)
            Stats = stats;
    }`
but this did not write in [https://github.com/agalasso/phd2client/blob/master/cxx/guider.h](url),so I could not use it.And I also found a bug in guider.h."#include <jsoncpp/json/json.h>" did not exit.It should change into "#include <json/json.h>".
